name: docker

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  docker-build-push:
    strategy:
      matrix:
        NODE_VERSION: [10, 12, 14, 16]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - run: "echo 'Building: ticto/node-softhsmv2:${{ matrix.NODE_VERSION }}'"

      - name: Build and push
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' && 'true' || 'false' }}
          tags: ticto/node-softhsmv2:${{ matrix.NODE_VERSION }}
          build-args: |
            NODE_VERSION=${{ matrix.NODE_VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build_server.outputs.digest }}

