name: docker

on:
  push:

jobs:
  docker-build-push:
    strategy:
      matrix:
        NODE_VERSION: [10.17.0, 12, 14, 16]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push featurecreep-server:latest
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/master' && 'true' || 'false' }}
          tags: ghcr.io/${{ github.event.repository.name }}:latest
          build-args: |
            NODE_VERSION="${{ matrix.NODE_VERSION }}"
      - name: Image digest
        run: echo ${{ steps.docker_build_server.outputs.digest }}

